### ISSUE TITLE
connect to existing catalog

### ISSUE THREAD

**Issue by anzmage** [facebookincubator/facebook-for-magento2#10]
how to connect to existing catalog, every time I try re-connect to the existing always force create new Ad account which is only allowed one account (test account)

**Comment by xiangminxufsu** [comment]
Hi, have you checked if the catalog/ad account under the same business manager? Usually they should be under the same business manager. Make sure you select the same business manager. Also if you can provide a screen record or screen shot it would be great

**Comment by anzmage** [comment]
![image](https://user-images.githubusercontent.com/224320/108659339-4a7a2980-74fd-11eb-8770-7a6cb63b4007.png)
I tried to connect existing account but not allowed, but if create a new one got this message
![image](https://user-images.githubusercontent.com/224320/108660008-75fd1400-74fd-11eb-93b9-86344b6afcb3.png)

**Comment by xiangminxufsu** [comment]
<img width="550" alt="Screen Shot 2021-02-21 at 9 07 51 PM" src="https://user-images.githubusercontent.com/8060655/108665080-ed449080-7488-11eb-8ae0-34d2a579eb10.png">
Hi were you able to see the reason like the screenshot?

**Comment by anzmage** [comment]
check this out

![image](https://user-images.githubusercontent.com/224320/108687748-aa86c500-7529-11eb-8a8f-df02ad0e555c.png)
![image](https://user-images.githubusercontent.com/224320/108687854-cb4f1a80-7529-11eb-9d7b-f7de6a78bd90.png)
![image](https://user-images.githubusercontent.com/224320/108687942-e6ba2580-7529-11eb-8982-ebfc5da69bc5.png)

**Comment by xiangminxufsu** [comment]
I am still thinking why the existed ad account is unselectable. When you move the mouse on the two ad accounts, what is the information?

**Comment by anzmage** [comment]
first account

![image](https://user-images.githubusercontent.com/224320/108791564-f54c1f80-75b1-11eb-9cc1-764aae43a461.png)

the second one

![image](https://user-images.githubusercontent.com/224320/108791626-1ca2ec80-75b2-11eb-9879-740b98f4f458.png)

**Comment by xiangminxufsu** [comment]
Interesting... So you don't own the business account? If it is this case,
ask the owner to add you as an admin in the business manger.

**Comment by anzmage** [comment]
no, I own the business account and admin as well, no other account

**Comment by xiangminxufsu** [comment]
Do you have only one FB account? Also how many business managers have you created? one or two? I want to make sure these two ads account is managed by the business manager you selected earlier in the flow. You can verify it by visiting business.facebook.com and select the business manager. You can see the ads account managed by the business manager.

![Uploading Screen Shot 2021-02-22 at 6.43.13 PM.png…]()

**Comment by anzmage** [comment]
Finally I can resolved this issue by creating business assets group then assign full permission to my FB account

![image](https://user-images.githubusercontent.com/224320/109448435-8e7aaa80-7a78-11eb-9e6b-c2d699440504.png)
