### ISSUE TITLE
facebook_software_system_requirements too long

### ISSUE THREAD

**Issue by akosglue** [facebookincubator/facebook-for-magento2#11]
I would like install this module on magento 2.2.9

However, when php bin/magento setup:upgrade, I get this error:

Module 'Facebook_BusinessExtension':
Upgrading data... An attribute code must not be less than 1 and more than 30 characters.

So it fails on this attribute: facebook_software_system_requirements which is indeed 37 characters long.

What can be done about it?

**Comment by xiangminxufsu** [comment]
Hi we will shorten it in our next release. Thanks for reporting it.

**Comment by xiangminxufsu** [comment]
Hi this is solved in our new release 1.2.5 Please update the extension and it would work
