### ISSUE TITLE
Items on facebook appear as "out of stock"

### ISSUE THREAD

**Issue by mbattistini** [facebookincubator/facebook-for-magento2#12]
magento 2.4.2
facebook-for-magento2 1.2.4

Most of the products are valid for the facebook/instagram catalog but "out of stock" even if they are available on magento.
Could there be a problem with the Multi-Source Inventory present on the latest versions of magento?

Thank you.

**Comment by nix0x00** [comment]
Not related to your question, but how did you get the magento products on facebook? I installed this extension but then I am confused as how to upload products to facebook?

**Comment by zlik** [comment]
> Not related to your question, but how did you get the magento products on facebook? I installed this extension but then I am confused as how to upload products to facebook?

@nix0x00, products will be uploaded to FB automatically on background right after you complete the onboarding flow and connect the FB assets. You can also initiate an on-demand upload from Stores -> Configuration -> Facebook -> Business Extension -> Catalog Management -> Push Products at any time. We'll update the user documentation to make it clearer.

**Comment by nix0x00** [comment]
> > Not related to your question, but how did you get the magento products on facebook? I installed this extension but then I am confused as how to upload products to facebook?
> 
> @nix0x00, products will be uploaded to FB automatically on background right after you complete the onboarding flow and connect the FB assets. You can also initiate an on-demand upload from Stores -> Configuration -> Facebook -> Business Extension -> Catalog Management -> Push Products at any time. We'll update the user documentation to make it clearer.

Can you please give me link to user documentation? I have already connected the extension with the page but neither its uploading the products automatically nor from the "Push Products" manually from catalog configuration.

**Comment by zlik** [comment]
> Can you please give me link to user documentation?

For now, we only have basic README and this [Help Center article](https://www.facebook.com/business/help/532749253576163) but a detailed user guide is coming up soon.

> I have already connected the extension with the page but neither its uploading the products automatically nor from the "Push Products" manually from catalog configuration.

Can you please share your `var/log/facebook-business-extension.log`?

**Comment by zlik** [comment]
> Most of the products are valid for the facebook/instagram catalog but "out of stock" even if they are available on magento.
> Could there be a problem with the Multi-Source Inventory present on the latest versions of magento?

@mbattistini, we've added support for multi-source inventory in [1.2.6](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.6). Can you please update and let me know if this is still an issue for you?

**Comment by nix0x00** [comment]
> > Can you please give me link to user documentation?
> 
> For now, we only have basic README and this [Help Center article](https://www.facebook.com/business/help/532749253576163) but a detailed user guide is coming up soon.
> 
> > I have already connected the extension with the page but neither its uploading the products automatically nor from the "Push Products" manually from catalog configuration.
> 
> Can you please share your `var/log/facebook-business-extension.log`?

I hope the doc is made available soon. 

the Logs:

https://github.com/nix0x00/newsletter_subscribers/raw/master/facebook-ext-business.log

**Comment by zlik** [comment]
@nix0x00, thanks! Can you please update the extension to the latest [`1.2.6`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.6) and try again? It has a fix for the `Deprecated Functionality: implode(): Passing glue string after array is deprecated.` error from your log.

**Comment by nix0x00** [comment]
> @nix0x00, thanks! Can you please update the extension to the latest [`1.2.6`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.6) and try again? It has a fix for the `Deprecated Functionality: implode(): Passing glue string after array is deprecated.` PHP error from your log.

I have updated it to 1.2.6, and upon clicking the settings in admin for this extension I get following error on the admin side.

https://raw.githubusercontent.com/nix0x00/newsletter_subscribers/master/facebook-1.2.6.log

**Comment by zlik** [comment]
> I have updated it to 1.2.6, and upon clicking the settings in admin for this extension I get following error on the admin side.
> 
> https://raw.githubusercontent.com/nix0x00/newsletter_subscribers/master/facebook-1.2.6.log

have you run `bin/magento setup:di:compile`?

**Comment by nix0x00** [comment]
> > I have updated it to 1.2.6, and upon clicking the settings in admin for this extension I get following error on the admin side.
> > https://raw.githubusercontent.com/nix0x00/newsletter_subscribers/master/facebook-1.2.6.log
> 
> have you run `bin/magento setup:di:compile`?

Okay I was able to do that configuration (setup this extension with facebook page). but This error continues. I have now tried to compile and upgrade many times, but still the same. I get this error when I click > Store > Config > Facebook >

https://raw.githubusercontent.com/nix0x00/newsletter_subscribers/master/facebook-1.2.6.log

**Comment by zlik** [comment]
@nix0x00, I'm looking into it. In the meantime, can you update to [`1.2.7`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.7), try again and open a new issue on Github if it's still happening for you. Thanks!

**Comment by nix0x00** [comment]
> @nix0x00, I'm looking into it. In the meantime, can you update to [`1.2.7`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.7), try again and open a new issue on Github if it's still happening for you? Thanks!

I have opened a new issue [at](https://github.com/facebookincubator/facebook-for-magento2/issues/23)
