### ISSUE TITLE
Cannot connect FB Business account

### ISSUE THREAD

**Issue by nattawutShopstack** [facebookincubator/facebook-for-magento2#125]
### Contact Details

nattawut@shopstack.asia

### What happened?

![image](https://user-images.githubusercontent.com/112054232/201848951-65ffac12-1bf4-44d4-8b3b-3c092db8eae6.png)

cannot connect FB Business account

### Magento Version

2.4.3

### Plugin Version

1.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iLenwy** [comment]
I encountered the same problem. By looking at the code, I found that I need to change the appId in view/adminhtml/templates/setup.phtml to the a application id you created in fb, but I tried to create different types of applications and the following errors were displayed.
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.
![image](https://user-images.githubusercontent.com/47706152/202100416-018a232f-1183-44ca-8c43-6f937527cb73.png)

I'm guessing it's the wrong type of app creation, but I don't know what kind of app to create. it's frustrating.

**Comment by dankocrama980** [comment]
Same problem here please fix

**Comment by raatool** [comment]
Same issue

**Comment by zlik** [comment]
This should be resolved now, please let us know if this is still an issue. Thx!

**Comment by iLenwy** [comment]
I uninstalled the extension pulled by composer，downloaded zip file on github and put it in app/code，copy the install-facebook-business-extension.sh script to Magento root folder，switch to Magento files owner user and run: ../install-facebook-business-extension.sh

run is ok
