### ISSUE TITLE
Configurable products with wrong url

### ISSUE THREAD

**Issue by shyopat** [facebookincubator/facebook-for-magento2#13]
Catalog synced successfully but having an issue with URL of configurable products example - configurable product has 5 variations of sizes, but configurable product URL in the Facebook catalog is showing with child product URL which is 404, so please look into this issue.

**Comment by xiangminxufsu** [comment]
Hi Thanks for reporting this. Could you give me an example of the wrong URL? A screenshot would also be helpful as well.

**Comment by shyopat** [comment]
![FB Catalog](https://user-images.githubusercontent.com/46157697/109381919-379f9480-7903-11eb-8512-7aedbb725e5f.JPG)

But Product actual URL is 
https://www.jaipurkurti.com/jaipur-kurti-angrakha-style-a-line-kurta-with-printed-palazzo-jkplz3898.html

**Comment by xiangminxufsu** [comment]
@zlik  could you take a look into this? Seems there are extra ```xxl``` in the url

**Comment by zlik** [comment]
@shyopat, this should be fixed in [1.2.5](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.5). Please try it out and let us know if this is still an issue. Thanks!
