### ISSUE TITLE
Can't connect without connecting to Instagram

### ISSUE THREAD

**Issue by chrisastley** [facebookincubator/facebook-for-magento2#14]
When I use the wizard to setup I can't get past the option for having to choose an Instagram account, I do have a page but it isn't eligible as it doesn't have enough established presence, but the setup doesn't let me skip the step so I can't configure?

Am I missing something?

**Comment by xiangminxufsu** [comment]
Hi,
You can unselect IG shopping on the first page in the wizards.

Let me know if you can’t find it.

**Comment by chrisastley** [comment]
Yes, thanks. Don't know how I missed it.
Does the plugin use the conversion API?

**Comment by xiangminxufsu** [comment]
Yeah it uses conversions api .
