### ISSUE TITLE
Setup not working

### ISSUE THREAD

**Issue by iiMuhamad** [facebookincubator/facebook-for-magento2#17]
Hi

After a successful installation on Magento 2.4, If i click setup the page is blank.

any idea?

Thanks 

https://user-images.githubusercontent.com/78938927/110450847-03835b00-80dd-11eb-90f5-27620e518b7b.mov

**Comment by xiangminxufsu** [comment]
Hi thanks for reporting it. What version of extension did you install? Is it the latest? what web browser did you use? Did you try another web browser?

**Comment by xiangminxufsu** [comment]
ok I will test it on 2.4 this afternoon, will keep you updated

**Comment by xiangminxufsu** [comment]
Hi did you run bin/magento: setup:upgrade command? I tested on 2.4 and it works
