### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Facebook\BusinessExtension\Model\System\Config::getOutOfStockThreshold()

### ISSUE THREAD

**Issue by akosglue** [facebookincubator/facebook-for-magento2#22]
m2 2.3.6
facebook/facebook-for-magento2 1.2.6

- open a product detail page via magento admin and save the product.
- error: Fatal error: Uncaught Error: Call to undefined method Facebook\BusinessExtension\Model\System\Config::getOutOfStockThreshold() in vendor/facebook/facebook-for-magento2/Model/Product/Feed/Builder/Inventory.php:126

so there is this call: $this->systemConfig->getOutOfStockThreshold()
if I look at this class
Facebook\BusinessExtension\Model\System\Config as SystemConfig;
I don't find any method like getOutOfStockThreshold

**Comment by zlik** [comment]
@akosglue, thanks for reporting. Confirmed, will ship a fix shortly.

**Comment by zlik** [comment]
Fixed in [`1.2.7`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.7).
