### ISSUE TITLE
Error: Cannot instantiate interface

### ISSUE THREAD

**Issue by nix0x00** [facebookincubator/facebook-for-magento2#23]
Hello,

Continuing my issue from [here]( https://github.com/facebookincubator/facebook-for-magento2/issues/12). I have now installed 1.2.7 on Magento 2.4.2, but I am getting following error when accessing `Admin > Stores > Config > Facebook`

Also getting this error when saving a product.

https://raw.githubusercontent.com/nix0x00/newsletter_subscribers/master/facebook-1.2.7.log

**Comment by zlik** [comment]
@nix0x00, thanks for opening a fresh task. Does `vendor/magento/module-inventory-api/Api/SourceRepositoryInterface.php` exist in your Magento codebase? Is Magento_InventoryApi module enabled in your `etc/config.php` file? Also, can you please try removing all files in the `./generated` directory and rerunning `bin/magento setup:di:compile`?

**Comment by nix0x00** [comment]
> @nix0x00, thanks for opening a fresh task. Does `vendor/magento/module-inventory-api/Api/SourceRepositoryInterface.php` exist in your Magento codebase? Is `Magento_InventoryApi` module enabled in your `etc/config.php` file? Also, can you please try removing all files in the `./generated` directory and rerunning `bin/magento setup:di:compile`?

@zlik  I have disabled all the modules for module-inventory*. As its a single store and no much of these extensions are required. Therefore, as recommended by [yireo](https://github.com/yireo/magento2-replace-all) I had used their replace modules in compose.json.

**Comment by zlik** [comment]
@nix0x00, thanks for sharing the details – super helpful for understanding the problem!

A quick fix should be enabling these 2 Magento modules:
* Magento_InventoryApi
* Magento_InventorySourceDeductionApi

Guide: https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.html

Also, we're going to prepare a new version of the extension later this week in which multi-source inventory will be optional so the extension will work without enabling those modules.

**Comment by duxabilii** [comment]
Similar issue from admin panel when try to save product
`( ! ) Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryApi\Api\SourceItemRepositoryInterface in /var/www/magento-multisite/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
[facebook_module_issue.zip](https://github.com/facebookincubator/facebook-for-magento2/files/6272181/facebook_module_issue.zip)
`

**Comment by nix0x00** [comment]
> @nix0x00, thanks for sharing the details – super helpful for understanding the problem!
> 
> A quick fix should be enabling these 2 Magento modules (you might need to add them back to `composer.json` as well):
> 
> * Magento_InventoryApi
> * Magento_InventorySourceDeductionApi
> 
> Guide: https://devdocs.magento.com/guides/v2.4/install-gde/install/cli/install-cli-subcommands-enable.html
> 
> Also, we're going to prepare a new version of the extension later this week in which multi-source inventory will be optional so the extension will work without enabling those modules.

Alright, that will be good. I shall wait for that version then for now as I do not want to enable these extra modules.

**Comment by nix0x00** [comment]
> * Magento_InventoryApi

I have installed the modules you mentioned and now I do not see that error. However, I get following message on browser when I click  `Stores > Config > Facebook >`

`An error has happened during application run. See exception log for details.`

**System.log :**

> Stack trace:
> #0 /var/www/websiteir/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Invento...', Array)
> #1 /var/www/websiteir/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Invento...')
> #2 /var/www/websiteir/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Invento...')
> #3 /var/www/websiteir/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Facebook\\Busine...')
> #4 /var/www/websiteir/vendor/magento/module-config/Model/Config/SourceFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->get('Facebook\\Busine...')
> #5 /var/www/websiteir/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(443): Magento\Config\Model\Config\SourceFactory->create('Facebook\\Busine...')
> #6 /var/www/websiteir/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(379): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel('Facebook\\Busine...')
> #7 /var/www/websiteir/vendor/magento/module-config/Block/System/Config/Form.php(394): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
> #8 /var/www/websiteir/vendor/magento/module-config/Block/System/Config/Form.php(316): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field), Object(Magento\Framework\Data\Form\Element\Fieldset), 'facebook/invent...', '', '')
> #9 /var/www/websiteir/vendor/magento/module-config/Block/System/Config/Form.php(256): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
> #10 /var/www/websiteir/vendor/magento/module-config/Block/System/Config/Form.php(202): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
> #11 /var/www/websiteir/vendor/magento/module-config/Block/System/Config/Form.php(542): Magento\Config\Block\System\Config\Form->initForm()
> #12 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(1110): Magento\Config\Block\System\Config\Form->_beforeToHtml()
> #13 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
> #14 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
> #15 /var/www/websiteir/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
> #16 /var/www/websiteir/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
> #17 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
> #18 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(522): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
> #19 /var/www/websiteir/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(32): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
> #20 /var/www/websiteir/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/website...')
> #21 /var/www/websiteir/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/website...', Array)
> #22 /var/www/websiteir/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/var/www/website...')
> #23 /var/www/websiteir/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
> #24 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Backend\Block\Template->_toHtml()
> #25 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
> #26 /var/www/websiteir/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache()
> #27 /var/www/websiteir/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
> #28 /var/www/websiteir/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
> #29 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
> #30 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
> #31 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('content', false)
> #32 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('content')
> #33 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('content', false)
> #34 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
> #35 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
> #36 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
> #37 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.col', false)
> #38 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
> #39 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main.col', false)
> #40 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
> #41 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
> #42 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
> #43 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.content', false)
> #44 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
> #45 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.content', false)
> #46 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
> #47 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
> #48 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
> #49 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
> #50 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
> #51 /var/www/websiteir/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('backend.page', false)
> #52 /var/www/websiteir/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
> #53 /var/www/websiteir/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
> #54 /var/www/websiteir/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
> #55 /var/www/websiteir/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout->getOutput()
> #56 /var/www/websiteir/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
> #57 /var/www/websiteir/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
> #58 /var/www/websiteir/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
> #59 /var/www/websiteir/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
> #60 /var/www/websiteir/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
> #61 /var/www/websiteir/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by zlik** [comment]
Reverted multi-source implementation in [1.4.0](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.4.0). Please update to this version and reopen the task if the issue is still happening for you. Thanks!
