### ISSUE TITLE
Items appear as "out of stock" when not tracking inventory in Magento

### ISSUE THREAD

**Issue by unknownTH** [facebookincubator/facebook-for-magento2#24]
facebook-for-magento2 1.2.7

We don't track inventory in Magento. Therefore, all items are always available. Unfortunately all items show as "Out of stock" when syncing to Facebook.

**Comment by zlik** [comment]
@unknownTH, this might be related to multi-source inventory changes we recently introduced. We just released [1.4.0](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.4.0) in which these changes are reverted. Can you please try it out and let us know if it's still an issue for you. Thanks!

**Comment by unknownTH** [comment]
@zlik, thanks for looking into the issue. I installed the version 1.4.0 and re-uploaded the items with the button in the Facebook settings within Magento backend. Unfortunately the items still show as "Out of stock" on Facebook.

**Comment by zlik** [comment]
@unknownTH, sorry it's still an issue for you. We're getting stock status and qty from product in [Inventory.php#L95-L109](https://github.com/facebookincubator/facebook-for-magento2/blob/master/Model/Product/Feed/Builder/Inventory.php#L95-L109). You could create a plugin around these two methods and override so products are always in stock if you don't track inventory in Magento. Will that work?

**Comment by unknownTH** [comment]
@zlik, I made a plugin to set the items to be always in stock. Thanks for your effort.
