### ISSUE TITLE
Syncing does not work

### ISSUE THREAD

**Issue by nexxoo** [facebookincubator/facebook-for-magento2#25]
Hello, I have a problem with the synchronization.
I have an around plugin for both retrievers to filter the exported products, so that only those products get into the feed, that are activated for it. So far so good, all products that are in the feed are uploaded correctly. But when a product is removed from the feed, it is not removed from the facebook catalog. 
The syncing feature in the Catalog Management section in the magento 2 backend is enabled.
I tried via cron 'facebook_business_extension_category_sync_cronjob' and via backend 'Push Products' resp. 'Upload to facebook' button.
  
How can I achieve this? Any help is appreciated.

Edit: I removed my around plugins and tried it with the native extension, but still the same outcome. Once a product is created in the facebook catalog it stays there and is not automatically removed, when it's not in an updated feed. 
This is the first time I'm working with the facebook catalog, so I'm sorry if this is just a setting in facebook?! But I went through all settings and couldn't find anything.

**Comment by xiangminxufsu** [comment]
Do you mean when you remove a product in magento catalog, it is not removed from facebook catalog? That sounds like a bug to me because we did remove the product from facebook catalog when it is being removed from magento

**Comment by nexxoo** [comment]
Thanks for your reply. Yes, that's what I meant. I did some tests today, by manually uploading the catalog to facebook via a csv file, with the replace option in the facebook backend set. And some products are removed, some are not. So I'm pretty sure it's a bug in facebook, not in your plugin and we can safely close this issue.
