### ISSUE TITLE
Facebook Catalog displays incorrect product links

### ISSUE THREAD

**Issue by jveins** [facebookincubator/facebook-for-magento2#26]
Hi, I was able to successfully complete the Facebook Business Extension installation and setup but I noticed that the website links generated for products on my facebook shop/catalog are incorrect. the links generated directs customers to my admin panel instead of the product page of my website. Please how can I fix this? See incorrect URL displayed in screenshots below.

![Screenshot 2021-04-12 at 19 49 25](https://user-images.githubusercontent.com/81697857/114468605-ab5fdd00-9be3-11eb-8ed6-97ec7b8d554b.png)
![wrong URL Screenshot 2021-04-10](https://user-images.githubusercontent.com/81697857/114468611-ae5acd80-9be3-11eb-8f8c-212fffd35c9e.png)
![Wrong URL_Screenshot 2021-04-10](https://user-images.githubusercontent.com/81697857/114468612-aef36400-9be3-11eb-9cff-24077f57ce4a.png)

**Comment by xiangminxufsu** [comment]
Hi thanks for reporting it. Which version are you at? We fixed it after 1.2.5 Could you try our latest version?

**Comment by jveins** [comment]
Hi, I just checked and i'm on version 1.2.3. I will try again with the latest version, thanks.
