### ISSUE TITLE
Class Magento\InventoryApi\Api\SourceRepositoryInterface does not exist 

### ISSUE THREAD

**Issue by bsimone** [facebookincubator/facebook-for-magento2#29]
During COMPILE, "magento/product-community-edition": "2.1.18", "facebook/facebook-for-magento2": "^1.4"

Probably related to https://github.com/facebookincubator/facebook-for-magento2/issues/23

Getting the error during setup:di:compile

Class used into: /Model/Config/Source/Product/InventorySource.php

**Comment by zlik** [comment]
@bsimone, we removed references to `SourceRepositoryInterface` and `/Model/Config/Source/Product/InventorySource.php` in `1.4.0`. Maybe cached somewhere? I would try removing `./generated`cache.

**Comment by zlik** [comment]
@bsimone, thank you for reporting the issue! Fixed in [1.4.1](https://github.com/facebookincubator/facebook-for-magento2/tree/1.4.1).
