### ISSUE TITLE
Feature Request: Trigger Product Feed Push from Admin

### ISSUE THREAD

**Issue by danbtl** [facebookincubator/facebook-for-magento2#4]
It would be helpful to have a button in the admin that can trigger an upload of the whole catalog.

Right now the the feed push is only triggered once during setup.

https://github.com/facebookincubator/facebook-for-magento2/blob/791716e68d9fc685e4f550a4ba67f9fe743481b3/Facebook/BusinessExtension/Controller/Adminhtml/Ajax/Fbfeedpush.php#L33

**Comment by zlik** [comment]
@danbtl, we're preparing a new version in which this feature, as well as some additional improvements have been implemented. please stay tune for updates, this should be rolled out very soon ;)

<img width="1095" alt="Screen Shot 2020-12-10 at 3 11 46 PM" src="https://user-images.githubusercontent.com/472255/101841285-7c810f80-3afa-11eb-9f3a-9721e4d0afa6.png">

**Comment by danbtl** [comment]
@zlik This looks great! Thanks for your quick reply.

**Comment by zlik** [comment]
This feature was rolled out in [`v1.2.3`](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.3).
