### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by MalvinMalvinsen** [facebookincubator/facebook-for-magento2#45]
Composer remove 

Visiting: Admin -> Catalog -> Products gives me the following error:

`1 exception(s):
Exception #0 (ReflectionException): Class Facebook\BusinessExtension\Model\Config\Source\Product\GoogleProductCategory does not exist

Exception #0 (ReflectionException): Class Facebook\BusinessExtension\Model\Config\Source\Product\GoogleProductCategory does not exist
<pre>#1 Magento\Framework\Code\Reader\ClassReader->getConstructor('Facebook\Busines...') called at [vendor/magento/framework/ObjectManager/Definition/Runtime.php:54]
#2 Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Facebook\Busines...') called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Facebook\Busines...', array()) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create('Facebook\Busines...', array()) called at [vendor/magento/framework/Validator/UniversalFactory.php:36]
#5 Magento\Framework\Validator\UniversalFactory->create('Facebook\Busines...') called at [vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php:642]
#6 Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource() called at [generated/code/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php:1181]
#7 Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getSource() called at [vendor/magento/module-catalog/Ui/Component/ColumnFactory.php:83]
#8 Magento\Catalog\Ui\Component\ColumnFactory->create(&Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor#000000006dac2edc000000006285487e#, &Magento\Framework\View\Element\UiComponent\Context#000000006dac2c6a000000006285487e#, array('label' => &Magento\Framework\Phrase#000000006dac2fe1000000006285487e#, 'dataType' => 'select', 'add_field' => true, 'visible' => true, 'filter' => 'select', '__disableTmpl' => array('label' => true), 'sortOrder' => 128)) called at [vendor/magento/module-catalog/Ui/Component/Listing/Columns.php:67]
#9 Magento\Catalog\Ui\Component\Listing\Columns->prepare() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:164]
#10 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(&Magento\Catalog\Ui\Component\Listing\Columns#000000006dac2d2b000000006285487e#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:161]
#11 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(&Magento\Ui\Component\Listing#000000006dac2d26000000006285487e#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:142]
#12 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(&Magento\Framework\View\Layout\Data\Structure#000000006dac20c7000000006285487e#, 'product_listing', array('attributes' => array('group' => '', 'component' => '', 'aclResource' => '', 'visibilityCondit...' => array())), &Magento\Framework\View\Layout\Interceptor#000000006dac2012000000006285487e#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#13 Magento\Framework\View\Layout\Generator\UiComponent->process(&Magento\Framework\View\Layout\Reader\Context#000000006dac2325000000006285487e#, &Magento\Framework\View\Layout\Generator\Context#000000006dac2305000000006285487e#) called at [vendor/magento/framework/View/Layout/GeneratorPool.php:81]
#14 Magento\Framework\View\Layout\GeneratorPool->process(&Magento\Framework\View\Layout\Reader\Context#000000006dac2325000000006285487e#, &Magento\Framework\View\Layout\Generator\Context#000000006dac2305000000006285487e#) called at [vendor/magento/framework/View/Layout.php:352]
#15 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#16 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#17 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#18 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#19 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:259]
#20 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:884]
#21 Magento\Framework\View\Layout->getBlock('menu') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#22 Magento\Framework\View\Layout\Interceptor->getBlock('menu') called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#23 Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog:...') called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#24 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog:...') called at [vendor/magento/module-catalog/Controller/Adminhtml/Product/Index.php:41]
#25 Magento\Catalog\Controller\Adminhtml\Product\Index->execute() called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Index/Interceptor.php:24]
#26 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#27 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/module-backend/App/AbstractAction.php:248]
#28 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#31 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor#000000006dac21ed000000006285487e#, &Closure#000000006dac21ec000000006285487e#, &Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#33 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#), NULL) called at [generated/code/Magento/Catalog/Controller/Adminhtml/Product/Index/Interceptor.php:39]
#34 Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/App/FrontController.php:186]
#35 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#, &Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor#000000006dac21ed000000006285487e#) called at [vendor/magento/framework/App/FrontController.php:118]
#36 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#37 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#38 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#39 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#), array(array('crankycyclops_di...', 'page_cache_from_...', 'default_store_se...', 'storeCookieValid...', 'install', 'configHash'), array('crankycyclops_di...'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#40 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000006dac2479000000006285487e#) called at [vendor/magento/framework/App/Http.php:116]
#41 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#42 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#43 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000006dac2467000000006285487e#) called at [index.php:39]
</pre>`

**Comment by Bashev** [comment]
You need to remove attributes which are related to facebook.

`select` * from eav_attribute where attribute_code like 'facebook_%' or attribute_code = 'google_product_category'`

but also is good idea to have uninstall scripts in the module.

**Comment by MalvinMalvinsen** [comment]
that solved the error, and cleaned the attributes, great!

**Comment by zlik** [comment]
Btw, we've released uninstall script in [v1.4.4](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.4.4).
