### ISSUE TITLE
module:uninstall not deleting the database tables so after uninstall & disabling of the module source_model classes in eav_attribute table will stay and will prevent admin user in admin to go to product pages  

### ISSUE THREAD

**Issue by goranhorvathr** [facebookincubator/facebook-for-magento2#50]
As the title says the bin/magento module:uninstall does not remove Facebook For Business database tables nor module created eav_attributes. We had to manually remove this when we were uninstalling this module because eav_attribute attributes will stay and will prevent admin user in admin to go to catalog/product with exception.

**Comment by zlik** [comment]
@goranhorvathr, thank you for reporting this issue. We've added it to our backlog. Will keep this task open to track progress. Thanks!

**Comment by wizzyto12** [comment]
We also have this problem. Its very frustrating to hire developers, cleaning someone else's mess.

**Comment by zlik** [comment]
Uninstall script was recently released in [v1.4.4](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.4.4). Closing this one.
