### ISSUE TITLE
Why force entity_id as content_id - Should allow to use SKU - This is in facebooks guide

### ISSUE THREAD

**Issue by maierb** [facebookincubator/facebook-for-magento2#51]
Hi I am reporting that your module forces the use of product_id for content_id and should be allowed to use SKU for content_Id as this is in facebooks own guidelines as seen here: https://www.facebook.com/business/help/120325381656392?id=725943027795860

People have been requesting this feature from your module for over 2 years (see https://github.com/facebookarchive/facebook-for-magento/issues/98 and https://github.com/facebookarchive/facebook-for-magento/issues/95)

And for some reason it still has not been incorporated even though in your own guides you recommend this. 

Now any merchant who installs this who have been using feeds as instructed by facebook will have their product catalog and all the history lost because you can't change a content ID, it will create a new product in facebook.

**Comment by zlik** [comment]
@maierb, thanks for reporting the issue. Agree with you. Adding support for both SKU and Magento ID to be used as `content_id` to the extension is one of our top priority tasks. Please stay tuned for updates.

**Comment by rangerz** [comment]
@zlik  Why close this issue? 
`content_id` is not yet using `sku`, not magento's `product id`

**Comment by rangerz** [comment]
@zlik 
Ignore here. I think it should be discussed here #34
