### ISSUE TITLE
Google product attributes & Facebook Attribute Group

### ISSUE THREAD

**Issue by HenryFaul** [facebookincubator/facebook-for-magento2#52]
I installed the latest version of the extension via composer into Magento 2.4 instance. 

As per the manual I don't see the referenced  Google product attributes or Facebook Attribute Group in my magento instance. The lack of these attributes causes an error on FB and products don't want to sync.

How do I get the Google product attributes & Facebook Attribute Group available in my instance?

**Comment by zlik** [comment]
@HenryFaul, have you run the `$ bin/magento setup:upgrade` command after installing the extension?
