### ISSUE TITLE
Multistore

### ISSUE THREAD

**Issue by agorbulin** [facebookincubator/facebook-for-magento2#53]
Hello.

Now it's possible to organize only one connection to FB, however Magento supports creation of  several websites.
Do you have plans to implement support of multistore connections to FB (own FB account for each Magento store)?
If yes, when release can be expected.

Thank you.

**Comment by zlik** [comment]
Hi @agorbulin, thanks for your note. We're definitely thinking about adding multi-store support later this year. Please stay tuned for updates.

**Comment by agorbulin** [comment]
Hello @zlik 
Are there any news regarding release of multistore functionality?

**Comment by pablobae** [comment]
Any news about this?  @zlik
