### ISSUE TITLE
View product details report 500 errors

### ISSUE THREAD

**Issue by will1033477817** [facebookincubator/facebook-for-magento2#58]
2021/06/15 10:17:48 [error] 24894#24894: *956277 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'FacebookAds\Object\ServerSide\UserData' not found in /opt/wwwdata/store/app/code/Facebook/Businesion/Helper/ServerEventFactory.php:28
Stack trace:
#0 /opt/wwwdata/store/app/code/Facebook/BusinessExtension/Helper/ServerEventFactory.php(167): Facebook\BusinessExtension\Helper\ServerEventFactory::newEvent('Search', '32342e4b-1792-4...')
#1 /opt/wwwdata/store/app/code/Facebook/BusinessExtension/Observer/Search.php(69): Facebook\BusinessExtension\Helper\ServerEventFactory::createEvent('Search', Array, '32342e4b-1792-4...')
#2 /opt/wwwdata/store/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Facebook\BusinessExtension\Observer\Search->execute(Object(Magento\Framework\Event\Observer))
#3 /opt/wwwdata/store/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Facebook\BusinessExtension\Observer\Search), Object" while readinnse header from upstream, client: 12.0.0.1, server: www.store, request: "GET /catalogsearch/result/?q=Otool HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "www.store.com", referrer: "/"

**Comment by Winfle** [comment]
@will1033477817 how did you solve this issue?
we have it right now
