### ISSUE TITLE
Can't Save Some Products in the Magento Admin

### ISSUE THREAD

**Issue by PromInc** [facebookincubator/facebook-for-magento2#6]
After installing this module we are receiving the following error when saving some products in the Magento admin:
`The stock item with the "11272" ID wasn't found. Verify the ID and try again.`

![image](https://user-images.githubusercontent.com/7319505/106170923-9a600d80-6156-11eb-91a8-ff3cda168365.png)

Magento Open Source v2.4.1

The bug exists in `app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php`

The `get` function for loading stock expects the `item_id` to be passed.  `item_id` is a unique identifier for the table - NOT for the product.  But the function call is passing the `product_id`.

`$stock = $this->_fbeHelper->createObject(StockItemRepository::class)->get($product->getId());`

The majority of the time the `item_id` and `product_id` do match in table `cataloginventory_stock_item`, but that is not a reliable assumption.

![image](https://user-images.githubusercontent.com/7319505/106171489-325df700-6157-11eb-8c8f-707f21c42abe.png)

```
mysql> SELECT count(*) FROM cataloginventory_stock_item;
+----------+
| count(*) |
+----------+
|    11393 |
+----------+
1 row in set (0.01 sec)

mysql> SELECT count(*) FROM cataloginventory_stock_item WHERE item_id <> product_id;
+----------+
| count(*) |
+----------+
|     9683 |
+----------+
1 row in set (0.00 sec)
```

This is the safe way to load the products stock based on the `product_id`:

```
git diff app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php
diff --git a/app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php b/app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php
index 61066758d..4dd9a3662 100644
--- a/app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php
+++ b/app/code/Facebook/BusinessExtension/Model/Feed/ProductFeed.php
@@ -56,14 +56,18 @@ class ProductFeed

     protected $enhanced_catalog_helper;

+    private $stockItemRepository;
+
     /**
      * Constructor
      * @param FBEHelper $helper
+     * @param \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry
      */
-    public function __construct(FBEHelper $helper, EnhancedCatalogHelper $enhanced_catalog_helper)
+    public function __construct(FBEHelper $helper, EnhancedCatalogHelper $enhanced_catalog_helper, \Magento\CatalogInventory\Api\StockRegistryInterface $stockRegistry)
     {
         $this->_fbeHelper = $helper;
         $this->enhanced_catalog_helper = $enhanced_catalog_helper;
+        $this->stockRegistry = $stockRegistry;
     }

     protected function isValidCondition($condition)
@@ -385,7 +389,8 @@ class ProductFeed

         $request = [];
         /** @var Item $stock */
-        $stock = $this->_fbeHelper->createObject(StockItemRepository::class)->get($product->getId());
+        $stock = $this->stockRegistry->getStockItem( $product->getId() );

         $request[self::ATTR_METHOD] = $method;
         $this->dedup_ids[$product->getId()] = true;
```

**Comment by xiangminxufsu** [comment]
Thanks for reporting it. We recently refactored the feed related code. I don't know if this issue is still applicable. @zlik

**Comment by PromInc** [comment]
Ok - good to know.  Interesting - my colleague added this module ~1 or 2 weeks ago and it was v1.2.0

```
cat app/code/Facebook/BusinessExtension/composer.json | grep version
  "version": "1.2.0",
```

I see the current is 1.2.3 and this file no longer exists.  I'll have to apply the updated module and evaluate that code.
