### ISSUE TITLE
Chaos FB product attributes in grid

### ISSUE THREAD

**Issue by rangerz** [facebookincubator/facebook-for-magento2#64]
In backend, the grid of products show all FB attributes. (columns and filter)
It's very chaos for experience !

![image](https://user-images.githubusercontent.com/3338473/125103453-fa61c500-e0a1-11eb-92c0-2cd54989cb57.png)

![image](https://user-images.githubusercontent.com/3338473/125103428-f33ab700-e0a1-11eb-951d-7a0e5a5e7711.png)

Please set `false` for `is_used_in_grid` and `is_filterable_in_grid` by default.
By the way, `is_visible_in_grid ` may also need to set `false`. I'm not sure this mapping for what UI.

https://github.com/facebookincubator/facebook-for-magento2/blob/c3d5942b9b91c3380c4a1c65590067e913039e5a/Setup/UpgradeData.php#L177-L179
https://github.com/facebookincubator/facebook-for-magento2/blob/c3d5942b9b91c3380c4a1c65590067e913039e5a/Setup/UpgradeData.php#L142-L144

The end, share the code snippet for manual to set those attributes
```PHP
$om = \Magento\Framework\App\ObjectManager::getInstance();
$eavConfig = $om->get(Magento\Eav\Model\Config::class);
$attributeConfig = $om->get(Facebook\BusinessExtension\Model\Config\ProductAttributes::class);
$attributes = array_keys($attributeConfig->getAttributesConfig());
array_push($attributes, 'google_product_category');

foreach ($attributes as $code) {
    $attribute = $eavConfig->getAttribute(Magento\Catalog\Model\Product::ENTITY, $code);
    $attribute->setData('is_used_in_grid', '0');
    $attribute->setData('is_filterable_in_grid', '0');
    $attribute->setData('is_visible_in_grid', '0');
    $attribute->save();
}
```

**Comment by zlik** [comment]
@rangerz, agree is this a very bad experience. We've removed the attributes from grid in the beta version of the extension (only available for selected sellers) but haven't ported it to the public version. We'll try to port the code that removes the attributes from grid shortly. Will keep this issue open until it's done.

**Comment by zlik** [comment]
We've removed the attributes from grid in v1.4.3. Please upgrade to the latest version and this issue should be addressed for you. Thanks!
