### ISSUE TITLE
Categories and Items not showing on Facebook

### ISSUE THREAD

**Issue by anthonyShahine** [facebookincubator/facebook-for-magento2#68]
Hello,
I am using Magento 2.3.5P2 and I installed facebook-for-magento2 1.4.3
I  Tried to push the categories and products  from Stores->Configuration->Facebook
The response is success, However, there's nothing on Facebook as I didn't see any item and category.
What could be the issue behind this behavior ?
I also noticed that the extension is adding a lot of attributes to the Magento Product, Should I use all of them ? because I am not using any of these attributes.

Awaiting your help

**Comment by mahmoudelbadrywork** [comment]
@anthonyShahine I'm having the same issue, can you let me know what was your solution?
