### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by websiteni** [facebookincubator/facebook-for-magento2#70]
How do you fully uninstall this module, including database entries?

I ran the following commands to disable the module:
php bin/magento module:disable --clear-static-content Facebook_BusinessExtension
php bin/magento setup:upgrade

However, when I removed the directory from app/code I got the following error when trying to edit a product:

Class Facebook\BusinessExtension\Model\Config\Source\Product\GoogleProductCategory does not exist

**Comment by janssensjelle** [comment]
@websiteni , remove the Facebook attributes created by the extension and you should be fine :-) 

- facebook_age_group
- facebook_is_assembly_required
- facebook_decor_style
- facebook_gender
- google_product_category
- facebook_pattern

**Comment by zlik** [comment]
We've released uninstall script in [v1.4.4](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.4.4). You can run:
`bin/magento module:uninstall -r Facebook_BusinessExtension`
Closing this issue.
