### ISSUE TITLE
Refunded and canceled orders

### ISSUE THREAD

**Issue by danceballos** [facebookincubator/facebook-for-magento2#75]
Due to the nature of our business, our store has a very high cancelation and refund rate (40 to 50%). 

We need to know what happens with canceled orders with this plugin.  This affects widely the ROAS and Revenue metrics inside the Facebook Business Manager. 

Is the cancelation being sent to Facebook when the order is canceled in Magento?

**Comment by Bashev** [comment]
Quick answer is - No. All events which are triggered in the module complete with purchase. Additionally when you make changes on products/categories they are pushed to FB to update catalog.

I'm not sure, but i think FB not receiving information about canceled or refunded orders. They track orders only to use data for remarketing (retargeting).
