### ISSUE TITLE
[Bug]: The price information under is invalid. Review for more details

### ISSUE THREAD

**Issue by pratikvs** [facebookincubator/facebook-for-magento2#86]
### Contact Details

pratik.sonawadekar@borngroup.com

### What happened?

Steps to reproduce

- Install magento version 2.4.3 EE version. 
- Install facebook/facebook-for-magento2 module.
- Do the Setup of the module under Stores > Facebook > Setup
- Go to  stores > configuration > Facebook > Business Extension > Catalog Management and click on Push Products.
Actual Response - Getting below error
`{"success":true,"feed_push_response":["{\"validation_status\":[{\"retailer_id\":\"1895\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]},{\"retailer_id\":\"1893\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]},{\"retailer_id\":\"1850\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]}]}"]}` 
Expected Result -
Should not get the above error.

The issue lies in the file vendor/facebook/facebook-for-magento2/Model/Product/Feed/Builder.php in the function buildProductEntry(Product $product).

A Quick Fix for the issue.

- Go to file vendor/facebook/facebook-for-magento2/Model/Product/Feed/Builder.php
- find the function buildProductEntry(Product $product) and find the below lines 
`self::ATTR_PRICE  => $this->getProductPrice($product),
 self::ATTR_SALE_PRICE => $this->getProductSalePrice($product),`

and ltrim the the currecy symbol from the$this->getProductPrice($product) and $this->getProductSalePrice($product) .

The price formatting is not happening correctly in the function public function formatPrice($price) present in the file vendor/facebook/facebook-for-magento2/Model/Product/Feed/Builder.php

### Magento Version

2.4.3 Enterprise Edition

### Plugin Version

1.4.3

### Relevant log output

```shell
{"success":true,"feed_push_response":["{\"validation_status\":[{\"retailer_id\":\"1895\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]},{\"retailer_id\":\"1893\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]},{\"retailer_id\":\"1850\",\"errors\":[{\"message\":\"The price information under is invalid. Review for more details\"}]}]}"]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by refaelgold** [comment]
can you write up the code please? Im trying to change it to
 ltrim($this->getProductPrice($product)),

**Comment by refaelgold** [comment]
self::ATTR_PRICE                => ltrim($this->getProductPrice($product),'₪'),
            self::ATTR_SALE_PRICE           => ltrim($this->getProductSalePrice($product),'₪'), 

i hope is that the right solution 

im getting : 
 Finished (response) ({"success":true,"feed_push_response":["{\"handles\":[\"AcwFgkVyVRWUX776jkzbvt40esI_u5Yd7dSFg0ZYS2QyfqzsOsuRoQrliSkmXAk9dyXNK1cYnhWcHz9dQYCqYXq5\"]}"]})

**Comment by refaelgold** [comment]
@pratikvs  i whould like for your reponse . Im stucking badly with that issue

**Comment by loopool** [comment]
It was a bug in Magento 2.4.3, 2.4.4 has fixed this issue.
https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde#diff-09a839078aa6453eb8fb437430724140207e2aa7214c3bb98bc7ced29fe39927R440-R443 fixed this issue
