### ISSUE TITLE
product have admin url link.

### ISSUE THREAD

**Issue by bracketdotbracket** [facebookincubator/facebook-for-magento2#9]
I downloaded this from facebook about a week ago, everything seems to be working fine except my product URL , they all seems to leading my Magento admin instead of the product.  Has anyone else come across this issue and does anyone know the fix. 

Thanks in advance.

**Comment by xiangminxufsu** [comment]
Thanks for reporting this. We are looking into it right now !

**Comment by bracketdotbracket** [comment]
Hi thanks for your quick response, I initially downloaded the module from facebook and i have since deleted it and installed the one from Github i now have a bigger problems the pixel seems to be working fine but my products are not being imported, i have also noticed a new "upload to facebook button"  which when i press says finished but no products are being pushed to my facebook catalog, i was really hoping to start advertising some new products but now i am unable to do so.

Can you please advise.

My Catalog says importing but it has been like for over a day, i have removed the connection multiple time and set it up again. i have deleted the module and reinstalled a few but no fix.

Thanks in advance.
![Screenshot 2021-02-18 at 11 11 25](https://user-images.githubusercontent.com/79165331/108348758-1a1f4c00-71da-11eb-9edd-776856f8aad9.jpg)

in the admin that says "push to facebook"
![Screenshot 2021-02-18 at 11 08 54](https://user-images.githubusercontent.com/79165331/108348466-ba28a580-71d9-11eb-9f56-b622f9bcacc7.jpg)

**Comment by xiangminxufsu** [comment]
Hi for the admin link issue, we already found a solution and will make a change later.
For the catalog sync issue, would you like to make a screen shot of logging? The file is is var/log/facebook-business-extension.log That will help us to detect issues.
Again, thanks for reporting those bugs. We will prioritize it since it looks very serious.

**Comment by xiangminxufsu** [comment]
I made a clean install today and find catalog sync works
The log file looks like this.
<img width="1259" alt="Screen Shot 2021-02-18 at 1 24 48 PM" src="https://user-images.githubusercontent.com/8060655/108423626-eef22800-71ec-11eb-904d-980f0c83bc41.png">

**Comment by bracketdotbracket** [comment]
> Hi for the admin link issue, we already found a solution and will make a change later.
> For the catalog sync issue, would you like to make a screen shot of logging? The file is is var/log/facebook-business-extension.log That will help us to detect issues.
> Again, thanks for reporting those bugs. We will prioritize it since it looks very serious.

Hi there, is the admin issue resolved in your latest release?

**Comment by xiangminxufsu** [comment]
Not yet, but it will be resolved in the next release. Will keep you updated.

**Comment by bracketdotbracket** [comment]
HI xiangminxufsu, 


THANK YOU SO MUCH FOR YOUR QUICK RESPONSES REALLY APPRECIATE IT.

Do you have a rough idea when you might release the next release as i just started a new business can really do with this module for the purpose of running ads, the admin link is currently causing a lot issues as you can imagine.

once again THANK YOU soo much for the quick replies.

**Comment by xiangminxufsu** [comment]
@zlik  do we have an ETA when this will get fixed? Next week?

**Comment by bracketdotbracket** [comment]
Hello @xiangminxufsu please do let me know when you release the new patch. Thank you.

**Comment by bracketdotbracket** [comment]
Any idea when we can expect the next release?

**Comment by zlik** [comment]
@bracketdotbracket, I'm looking into this now. How many websites/stores do you currently have in Magento? Is it ok if we take the product URL in the default store for the feed?

**Comment by zlik** [comment]
@bracketdotbracket, this should be fixed now. Please see the latest [1.2.5](https://github.com/facebookincubator/facebook-for-magento2/releases/tag/1.2.5) release.
